"""created quizzes and events models

Revision ID: 5ed86e6b0498
Revises: a0ecf1e0a290
Create Date: 2025-06-29 13:59:05.985544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed86e6b0498'
down_revision: Union[str, Sequence[str], None] = 'a0ecf1e0a290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('media_url_one', sa.String(length=255), nullable=True),
    sa.Column('media_url_two', sa.String(length=255), nullable=True),
    sa.Column('media_url_three', sa.String(length=255), nullable=True),
    sa.Column('media_url_four', sa.String(length=255), nullable=True),
    sa.Column('media_url_five', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('question', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('media_url_one', sa.String(length=255), nullable=True),
    sa.Column('media_url_two', sa.String(length=255), nullable=True),
    sa.Column('media_url_three', sa.String(length=255), nullable=True),
    sa.Column('answer_one', sa.String(length=255), nullable=True),
    sa.Column('answer_two', sa.String(length=255), nullable=True),
    sa.Column('answer_three', sa.String(length=255), nullable=True),
    sa.Column('answer_four', sa.String(length=255), nullable=True),
    sa.Column('answer_five', sa.String(length=255), nullable=True),
    sa.Column('correct_answer', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('visibility', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_id'), 'quizzes', ['id'], unique=False)
    op.create_table('event_interests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interest_type', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_interests_id'), 'event_interests', ['id'], unique=False)
    op.create_table('quiz_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_interactions_id'), 'quiz_interactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_interactions_id'), table_name='quiz_interactions')
    op.drop_table('quiz_interactions')
    op.drop_index(op.f('ix_event_interests_id'), table_name='event_interests')
    op.drop_table('event_interests')
    op.drop_index(op.f('ix_quizzes_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
