"""add relationship between comment_id and parent_comment_id

Revision ID: 6c0f3d39c891
Revises: fc7069e47f54
Create Date: 2025-06-28 22:00:18.301423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0f3d39c891'
down_revision: Union[str, Sequence[str], None] = 'fc7069e47f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
