"""initial

Revision ID: a368f8e43df6
Revises: 
Create Date: 2025-07-19 00:12:52.484169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a368f8e43df6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('school', sa.String(length=255), nullable=True),
    sa.Column('semester', sa.String(length=255), nullable=True),
    sa.Column('year', sa.String(length=255), nullable=True),
    sa.Column('exam_type', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('media_url_one', sa.String(length=255), nullable=True),
    sa.Column('media_url_two', sa.String(length=255), nullable=True),
    sa.Column('media_url_three', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_papers_id'), 'exam_papers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_papers_id'), table_name='exam_papers')
    op.drop_table('exam_papers')
    # ### end Alembic commands ###
