"""course db added

Revision ID: a7039782f6af
Revises: a368f8e43df6
Create Date: 2025-07-19 00:52:19.705961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7039782f6af'
down_revision: Union[str, Sequence[str], None] = 'a368f8e43df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('media_url_1', sa.String(length=255), nullable=True),
    sa.Column('media_url_2', sa.String(length=255), nullable=True),
    sa.Column('media_url_3', sa.String(length=255), nullable=True),
    sa.Column('media_url_4', sa.String(length=255), nullable=True),
    sa.Column('media_url_5', sa.String(length=255), nullable=True),
    sa.Column('media_url_6', sa.String(length=255), nullable=True),
    sa.Column('media_url_7', sa.String(length=255), nullable=True),
    sa.Column('media_url_8', sa.String(length=255), nullable=True),
    sa.Column('media_url_9', sa.String(length=255), nullable=True),
    sa.Column('media_url_10', sa.String(length=255), nullable=True),
    sa.Column('media_url_11', sa.String(length=255), nullable=True),
    sa.Column('media_url_12', sa.String(length=255), nullable=True),
    sa.Column('media_url_13', sa.String(length=255), nullable=True),
    sa.Column('media_url_14', sa.String(length=255), nullable=True),
    sa.Column('media_url_15', sa.String(length=255), nullable=True),
    sa.Column('resource_url_1', sa.String(length=255), nullable=True),
    sa.Column('resource_url_2', sa.String(length=255), nullable=True),
    sa.Column('resource_url_3', sa.String(length=255), nullable=True),
    sa.Column('resource_url_4', sa.String(length=255), nullable=True),
    sa.Column('resource_url_5', sa.String(length=255), nullable=True),
    sa.Column('marks_for_pass', sa.Integer(), nullable=True),
    sa.Column('applicable_grade', sa.String(length=10), nullable=True),
    sa.Column('applicable_level', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('course_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Integer(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_questions_id'), 'course_questions', ['id'], unique=False)
    op.create_table('course_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['course_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_answers_id'), 'course_answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_answers_id'), table_name='course_answers')
    op.drop_table('course_answers')
    op.drop_index(op.f('ix_course_questions_id'), table_name='course_questions')
    op.drop_table('course_questions')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
