"""removed named enums

Revision ID: c002dd835a4a
Revises: 7acba44ea3ea
Create Date: 2025-06-25 15:45:18.303672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c002dd835a4a'
down_revision: Union[str, Sequence[str], None] = '7acba44ea3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher_data', 'teaching_experience',
               existing_type=postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'EXPERIENCED', 'MASTER', name='teachingexperienceenum'),
               type_=sa.String(length=25),
               existing_nullable=True)
    op.alter_column('users', 'sex',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='sexenum'),
               type_=sa.String(length=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sex',
               existing_type=sa.String(length=6),
               type_=postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='sexenum'),
               existing_nullable=True)
    op.alter_column('teacher_data', 'teaching_experience',
               existing_type=sa.String(length=25),
               type_=postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'EXPERIENCED', 'MASTER', name='teachingexperienceenum'),
               existing_nullable=True)
    # ### end Alembic commands ###
