"""add ratings column to post_ratings

Revision ID: fc7069e47f54
Revises: cc2366eaf3be
Create Date: 2025-06-28 11:38:12.637308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7069e47f54'
down_revision: Union[str, Sequence[str], None] = 'cc2366eaf3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_ratings', sa.Column('ratings', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_ratings', 'ratings')
    # ### end Alembic commands ###
